version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    volumes:
      - ./web/.docker/nginx.conf:/etc/nginx/nginx.conf

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile.prod
