version: '3'

services:
  server:
    build: .

  web:
    build: ./web
    volumes:
      - ./web:/usr/app

  websocket:
    build: ./websocket
    volumes:
      - ./websocket:/usr/app

  maildev:
    image: djfarrelly/maildev
    container_name: u_maildev
    restart: always
    labels:
      - traefik.http.routers.maildev.rule=Host(`maildev.localhost`)
      - traefik.http.services.maildev.loadbalancer.server.port=80
