version: '3'

services:
  server:
    build: .
    restart: always

  web:
    build:
      context: ./web
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - ./web/.docker/nginx.conf:/etc/nginx/nginx.conf

  websocket:
    build:
      context: ./websocket
      dockerfile: prod.Dockerfile
    restart: always
