<?php declare(strict_types=1);

return [
    'profile' => [
        'edit' => 'profile.edit',
    ],
    'users' => [
        'view_section' => 'users.view_section',
        'view_all' => 'users.view_all',
        'edit_all' => 'users.edit_all',
        'create' => 'users.create',
        'delete_all' => 'users.delete_all',
    ],
    'roles' => [
        'view_section' => 'roles.view_section',
        'view_all' => 'roles.view_all',
        'edit_all' => 'roles.edit_all',
    ],
    'equipments' => [
        'view_section' => 'equipments.view_section',
        'view_all' => 'equipments.view_all',
        'view_own' => 'equipments.view_own',
        'edit_all' => 'equipments.edit_all',
        'edit_own' => 'equipments.edit_own',
        'create' => 'equipments.create',
        'delete_all' => 'equipments.delete_all',
        'delete_own' => 'equipments.delete_own',
        'files' => [
            'view_all' => 'equipments.files.view_all',
            'view_own' => 'equipments.files.view_own',
            'download_all' => 'equipments.files.download_all',
            'download_own' => 'equipments.files.download_own',
            'edit_all' => 'equipments.files.edit_all',
            'edit_own' => 'equipments.files.edit_own',
            'create' => 'equipments.files.create',
            'delete_all' => 'equipments.files.delete_all',
            'delete_own' => 'equipments.files.delete_own',
        ],
        'config' => [
            'view_section' => 'equipments.config',
            'view_all' => 'equipments.config',
            'edit_all' => 'equipments.config',
            'edit_own' => 'equipments.config',
            'create' => 'equipments.config',
            'delete_all' => 'equipments.config',
            'delete_own' => 'equipments.config',
        ],
    ],
    'requests' => [
        'view_section' => 'requests.view_section',
        'view_all' => 'requests.view_all',
        'view_own' => 'requests.view_own',
        'view_assign' => 'requests.view_assign',
        'edit_all' => 'requests.edit_all',
        'edit_own' => 'requests.edit_own',
        'edit_assign' => 'requests.edit_assign',
        'create' => 'requests.create',
        'delete_all' => 'requests.delete_all',
        'delete_own' => 'requests.delete_own',
        'delete_assign' => 'requests.delete_assign',
        'comments' => [
            'view_all' => 'requests.comments.view_all',
            'edit_all' => 'requests.comments.edit_all',
            'edit_own' => 'requests.comments.edit_own',
            'create' => 'requests.comments.create',
            'delete_all' => 'requests.comments.delete_all',
            'delete_own' => 'requests.comments.delete_own',
        ],
        'files' => [
            'view_all' => 'requests.files.view_all',
            'view_own' => 'requests.files.view_own',
            'download_all' => 'requests.files.download_all',
            'download_own' => 'requests.files.download_own',
            'edit_all' => 'requests.files.edit_all',
            'edit_own' => 'requests.files.edit_own',
            'create' => 'requests.files.create',
            'delete_all' => 'requests.files.delete_all',
            'delete_own' => 'requests.files.delete_own',
        ],
        'config' => [
            'view_section' => 'requests.config.view_section',
            'view_all' => 'requests.config.view_all',
            'edit_all' => 'requests.config.edit_all',
            'edit_own' => 'requests.config.edit_own',
            'create' => 'requests.config.create',
            'delete_all' => 'requests.config.delete_all',
            'delete_own' => 'requests.config.delete_own',
        ],
    ],
    'global' => [
        'settings' => [
            'edit' => 'global.settings.edit',
        ],
        'manifest' => [
            'edit' => 'global.manifest.edit',
        ],
    ],
];
