version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
  websocket:
    driver: ${NETWORKS_DRIVER}
  frontend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  php-fpm:
    build: ./php-fpm
    container_name: urepairpc_php_fpm
    restart: always
    volumes:
      - ${APP_PATH}:/var/www
    networks:
      - backend
      - websocket

  nginx:
    build: ./nginx
    container_name: urepairpc_nginx
    restart: always
    volumes:
      - ${APP_PATH}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - frontend
      - backend
      - websocket
    depends_on:
      - php-fpm

  mysql:
    build: ./mysql
    container_name: urepairpc_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    networks:
      - backend
      - websocket

  redis:
    build: ./redis
    container_name: urepairpc_redis
    restart: always
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
      - websocket
