version: '3'

services:
  traefik:
    image: traefik:v2.2
    container_name: u_traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080

  php-fpm:
    build: ./php-fpm
    container_name: u_php_fpm
    restart: always
    volumes:
      - ../:/var/www

  nginx:
    build: ./nginx
    container_name: u_nginx
    restart: always
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    labels:
      - traefik.http.routers.nginx.rule=Host(`urepairpc.localhost`) && PathPrefix(`/api/`)
      - traefik.http.routers.nginx.entrypoints=web

  web:
    build: ./web
    container_name: u_web
    restart: always
    volumes:
      - ../web:/usr/app
    labels:
      - traefik.http.routers.web.rule=Host(`urepairpc.localhost`)
      - traefik.http.routers.web.entrypoints=web

  websocket:
    build: ./websocket
    container_name: u_websocket
    volumes:
      - ../websocket:/usr/app
    labels:
      - traefik.http.routers.websocket.rule=Host(`urepairpc.localhost`) && Path(`/ws/`)
      - traefik.http.routers.websocket.entrypoints=web

  mysql:
    build: ./mysql
    container_name: u_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    build: ./redis
    container_name: u_redis
    restart: always
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: u_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_USER=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  grafana:
    image: grafana/grafana:latest
    container_name: u_grafana
    restart: always
    user: "0"
    volumes:
      - ${DATA_PATH}/grafana:/var/lib/grafana
    ports:
      - 3000:3000

  maildev:
    image: djfarrelly/maildev
    container_name: u_maildev
    restart: always
    ports:
      - 1080:80
      - 25:25
