version: '3'

services:
  traefik:
    image: traefik:v2.2
    container_name: u_traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080

  php-fpm:
    build: ./php-fpm
    container_name: u_php_fpm
    restart: always
    volumes:
      - ${APP_PATH}:/var/www

  nginx:
    build: ./nginx
    container_name: u_nginx
    restart: always
    volumes:
      - ${APP_PATH}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    labels:
      - traefik.http.routers.nginx.rule=Host(`urepairpc.localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.nginx.entrypoints=web

  web:
    build: ./web
    container_name: u_web
    volumes:
      - ${APP_PATH}web:/usr/app
    labels:
      - traefik.http.routers.web.rule=Host(`urepairpc.localhost`)
      - traefik.http.routers.web.entrypoints=web

  mysql:
    build: ./mysql
    container_name: u_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql

  redis:
    build: ./redis
    container_name: u_redis
    restart: always
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - 6379:6379
