name: Websocket

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env.testing to .env
        run: cp .env.testing .env
      - name: Init core containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d traefik rabbitmq
      - name: Run container
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from websocket --build websocket
